# .github/workflows/release.yml
name: Build & Release WP plugin asset

on:
  push:
    tags: ["v*"]

permissions:
  contents: write # <— fondamentale per creare la release

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      # ... resto invariato ...
      - name: Pubblica la Release con asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: xupport-gf-assistenza-${{ github.ref_name }}.zip
